First step in integration
ORNL/zambeze pull request #77
Opened 2022-11-15 04:13 UTC by JoshuaSBrown

First step, in integrating the messaging infrastructure into Zambeze.

2022-11-15 16:03 UTC, tskluzac requested changes

2022-11-15 16:03 UTC, tskluzac commented on zambeze/orchestration/processor.py
> +                msg_template[1]["body"]["cmd"] = [
Repeat comment from earlier (are we editing second element of list? and can this be done cleaner)

2022-11-15 16:05 UTC, JoshuaSBrown commented on zambeze/orchestration/processor.py
> +                await self._queue_client.send(ChannelType.ACTIVITY, immutable_msg_move)
The first is doing a transfer between Globus imports the second is moving files from and enpoint to somewhere else on the POSIX file system. I should probably add some comments, or do you have some ideas for better variable names?

2022-11-15 16:07 UTC, JoshuaSBrown commented on zambeze/orchestration/processor.py
> +                msg_template_move[1]["body"]["cmd"] = [
msg_template_move is a tuple the first element is the MessageType, and the second element is a dict which contains the message envelope as defined in the detailed design document. Do you have any suggestions?

2022-11-15 16:07 UTC, JoshuaSBrown commented on zambeze/orchestration/processor.py
> +                local_globus_uri = local_globus_uri + source_file_name
Good catch, I did not know that. Yes.

2022-11-15 16:12 UTC, JoshuaSBrown commented on zambeze/orchestration/processor.py
> +                msg_template_move[1]["body"]["cmd"] = [
Maybe we could have a template object that is returned. 

```Python
class MessageTemplate:
 
 def __init__(self):
    self.__type = MessageType.ACTIVITY
    self.__message = { ...Template... }

 @property
  def type(self) -> MessageType:
    return self.__type
  
```

2022-12-14 14:44 UTC, JoshuaSBrown commented
The following changes have occurred in this PR. The PluginMessageHelper class was split into two separate classes to follow the separation of concerns principle and the single responsibility principle. Red indicates removal Blue indicates a new addition.

![image](https://user-images.githubusercontent.com/4664476/207626322-3ebb3a34-f71b-4aa4-9c15-8176bbde800a.png)

![image](https://user-images.githubusercontent.com/4664476/207626429-62dc4bf9-f974-407b-85ae-f2c0e18c21cb.png)

![image](https://user-images.githubusercontent.com/4664476/207626509-2816e28a-31f7-4c62-9857-7cc7c86d586a.png)

2022-12-16 03:01 UTC, JoshuaSBrown commented
@wilkinson This is ready for your input. @tskluzac I have tried to address your concerns here as well.

2022-12-22 18:12 UTC, merged